select * from bus
select * from busline
select * from busdriver
select * from busride
select * from driver
select * from passenger
select * from stationtobus
select * from station
select * from ticket
select * from travelpayment

select count(*) from bus
select count(*) from busline
select count(*) from busdriver
select count(*) from busride
select count(*) from driver
select count(*) from passenger
select count(*) from stationtobus
select count(*) from station
select count(*) from ticket
select count(*) from travelpayment
